name: Kevin Zhong
author: Kevin Zhong
github: dwarfattack
title: Kevin Zhong's Blog
description: A diary.
theme: jekyll-theme-cayman
permalink: /blog/:year/:month/:day/:title
repository: dwarfattack/dwarfattack.github.io
include: [_redirects, _config.yml]
url: kjzhong.me

plugins:
  - jekyll-sitemap
  - github-pages

