name: kjzhong
author: kjzhong
# github: dwarfattack
title: kjblog
description: This website is still in very early development. Please be patient with me while I work on it!
theme: jekyll-theme-cayman
permalink: /blog/:year/:month/:day/:title
repository: dwarfattack/dwarfattack.github.io
include: [_redirects, _config.yml]
url: kjzhong.me

plugins:
  - jekyll-sitemap
  - github-pages

