name: Kevin Zhong
title: Kevin Zhong's Blog
description: A diary for my progress through life and thoughts.
theme: jekyll-theme-cayman
permalink: /blog/:year/:month/:day/:title
repository: dwarfattack/dwarfattack.github.io
